#! /bin/sh

### BEGIN INIT INFO
# Provides:		tmux
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	OpenBSD Secure Shell server
### END INIT INFO

set -e
. /lib/lsb/init-functions
export PATH="${PATH:+$PATH:}/usr/sbin:/sbin:/usr/bin/"

case "$1" in
  start)
	su jarhu -l -c "/usr/bin/tmux-session restore"
    while((1))
    do
        sleep 30
        su jarhu -l -c "/usr/bin/tmux-session save" 
    done
	;;
  stop)
	#su jarhu -l -c "/usr/bin/tmux-session save"
    echo "stop tmux"
	;;

  *)
	log_action_msg "Usage: $0 {start|stop}" || true
	exit 1
esac

exit 0
